before_install: npm install npm@latest --global
cache:
  directories:
    - $HOME/.npm
dist: xenial
install: npm ci || (rm -rf node_modules && npm install)
language: node_js
matrix:
  include:
    - env: TYPE=integration
      node_js: 10
    - env: TYPE=integration
      node_js: 12
    - env: TYPE=unit
      node_js: 10
    - env: TYPE=unit
      node_js: 12
